theme: jekyll-theme-minimal
title: Max Austin
logo: "/img/profPic.png?raw=true"
description : >
    BSc. Computer Science, Utah Valley University
    <br><br>
    Thanks for checking my page out! Please take a look around. You can contact me using the form below.
    <br><br>
    <form action="//formspree.io/your@email.com" method="POST">
    <p>Email: </p><input type="email" name="_replyto"><br />
    <p>Subject: </p><input type="text" name="subject"><br />
    <p>Description: </p><input type="text" name="description"><br />
    <input type="submit" value="Send">
    </form>
    <br>
    <input type="hidden" name="_next" value="thanks.md" />
    
