theme: jekyll-theme-minimal
title: Max Austin
logo: "/img/profPic.png?raw=true"
description : >
    BSc. Computer Science, Utah Valley University
    <br><br>
    Thanks for checking my page out! Please take a look around. You can contact me using the link below.
    <br>
    <a href="contact.md">Contact</a>
