theme: jekyll-theme-minimal
title: Max Austin
logo: "/img/profPic.png?raw=true"
description : >
    BSc. Computer Science, Utah Valley University
    <br><br>
    <h3>Contents</h3>
    <ul>
        <li><a href="index">Portfolio</a></li>
        <li><a href="contact">Contact</a></li>
    </ul><br>
    Thanks for checking my page out! Please take a look around. You can contact me using the link above.
    <br>
