title: Max Austin
description : >
    BSc. Computer Science, Utah Valley University
    <br>
    Thanks for checking my page out! Please take a look around. You can contact me using any method below.
    <br>
theme: jekyll-theme-midnight